config/routes.rb
Rails.application.routes.draw do
  root to: "characters#index"
  resources :characters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :age
    validates :detail
  end

  def self.search(keyword)
    where('name like ?', "%#{keyword}%")
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @keyword = params[:keyword]
    @characters = if @keyword.present?
      Character.order(created_at: :desc).search(@keyword).page(params[:page]).per(5) # 検索結果にページネーションを適用
    else
      Character.order(created_at: :desc).page(params[:page]).per(5) # 1ページあたり5件表示
    end
  end

  def new
    @character = Character.new()
  end
  
  def create
    @character = Character.new(params_character)
    if @character.save
      redirect_to characters_path
    else
      render :new
    end
    
  end
  def edit
    
  end
  def update
    
  end
  def destroy
    
  end

  private
  def params_character
    params.require(:character).permit(:name, :age, :detail)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/index.html.erb
<h1>キャラクターBooks</h1>
<div></div>
<div>
  <%= link_to 'キャラクターを作成する', new_character_path %>
</div>
<div>
  <%= form_with local: true, method: :get do |f| %>
    <%= f.text_field :keyword %>
    <%= f.submit '検索' %>
  <% end %>
</div>
<div>
  <%= paginate @characters %>
  <% @characters.each do |character| %>
    <div>
      <%= character.name %><%= character.age %><br>
      <%= character.detail %>
    </div>
  <% end %>
  <%= paginate @characters %>
</div>

app/views/characters/new.html.erb
<h1>キャラクターの新規作成</h1>
<%= form_with model: @character do |f| %>
  <%= f.label :name, '名前' %><br>
  <%= f.text_field :name, placeholder: '入力してください' %><br>
  <%= f.label :age, '年齢' %><br>
  <%= f.number_field :age, placeholder: '入力してください' %><br>
  <%= f.label :detail, '詳細設定' %><br>
  <%= f.text_area :detail, placeholder: '入力してください' %><br>
  <%= f.submit '作成' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchFromIndexApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>